name: Log Secrets (Test Only)

on:
  workflow_dispatch:

jobs:
  log-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Log secrets
        run: |
          echo "NAME: ${{ secrets.NAME }}"
          echo "AGE: ${{ secrets.AGE }}"
          echo "EMAIL: ${{ secrets.EMAIL }}"
