name: Log Secrets (Test Only)

on:
  workflow_dispatch:

jobs:
  log-secrets:
    runs-on: ubuntu-latest
    environment: Test  # important if you're using environment-scoped secrets
    steps:
      - name: Log secrets (indirect)
        run: |
          echo "NAME (secret): ${{ secrets.NAME }}"
          echo "AGE (secret): ${{ secrets.AGE }}"
          echo "EMAIL (secret): ${{ secrets.EMAIL }}"
      
      - name: Log env vars (non-secret)
        run: |
          echo "NAME (env): ${{ vars.NAME }}"
          echo "AGE (env): ${{ vars.AGE }}"
          echo "EMAIL (env): ${{ vars.EMAIL }}"
