name: Log Secrets (Test Only)

on:
  workflow_dispatch:

jobs:
  log-secrets:
    runs-on: ubuntu-latest
    env:   # These will be set as environment variables for all steps
      NAME: ${{ secrets.NAME }}
      AGE: ${{ secrets.AGE }}
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - name: Log secrets directly
        run: |
          echo "NAME (secret): ${{ secrets.NAME }}"
          echo "AGE (secret): ${{ secrets.AGE }}"
          echo "EMAIL (secret): ${{ secrets.EMAIL }}"
      - name: Log secrets as environment variables
        run: |
          echo "NAME (env): $NAME"
          echo "AGE (env): $AGE"
          echo "EMAIL (env): $EMAIL"
